version: 0.2

phases:
  install: #Makes sure that npm and serverless is installed
    commands:
      - apt-get update
      - apt-get -y install python3-pip python-dev 
      - pip install --user pipenv
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
    finally:
      - echo "Done with install phase"   
  pre_build: #Makes sure that app specific dependencies are installed from requirements
    commands:
      - pwd
      - ls
      - python3 -m pip install --user virtualenv
      - virtualenv -p python3 a
      - . a/bin/activate
      - npm install serverless-python-requirements
      - pip install -r requirements.txt
    finally:
      - echo "Done with pre_build phase"
  post_build: #For Deployment
    commands:
      - echo $SHELL
      - sh deploy.sh
    finally:
      - echo "Done with post_build phase"

      
#- pip install numpy
      # - mkdir python-project
      # - ls
      # - pip install --upgrade pip / --target=./
      # - pip install -r requirements.txt \
      # - pip install numpy --target=./
      # - pipenv install -r requirements.txt
      # - pipenv install numpy      