version: 0.2

phases:
  install: #Makes sure that np
     commands:
       - apt-get update
       - apt-get -y install python3-pip python-dev 
       - npm install --silent --no-progress -g npm
       - npm install --silent --no-progress -g serverless 
  pre_build:
    commands:
      -  sls plugin install -y -n serverless-python-requirements
      -  pip install -r requirements.txt