version: 0.2

phases:
  install: #Makes sure that np
     commands:
       - apt-get update
       - apt-get -y install python3-pip python-dev 
       - npm install --silent --no-progress -g npm
       - npm install --silent --no-progress -g serverless 
     finally:
       - echo "Done with install phase"   
  pre_build:
    commands:
      -  pip install -r requirements.txt
    finally:
       - echo "Done with pre_build phase"     
  post_build:
    comands:
      - echo $SHELL
      - sh deploy.sh     
    finally:
       - echo "Done with post_build phase"            