version: 0.2

phases:
  install: #Makes sure that npm and serverless is installed
    commands:
      - apt-get update
      - apt-get -y install python3-pip python-dev 
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
      # - npm install --save serverless-python-requirements
    finally:
      - echo "Done with install phase"   
  pre_build: #Makes sure that app specific dependencies are installed from requirements
    commands:
      - pwd
      - ls
      - pip install -r requirements.txt --target=./
    finally:
      - echo "Done with pre_build phase"
  post_build: #For Deployment
    commands:
      - sh deploy.sh
    finally:
      - echo "Done with post_build phase"

      
  #- pip install numpy
      # - mkdir python-project
      # - ls
      # - pip install --upgrade pip / --target=./
      # - pip install -r requirements.txt \
      # - pip install numpy --target=./
      # - pipenv install -r requirements.txt
      # - pipenv install numpy      
      # - python3 -m pip install --user virtualenv
      # - virtualenv -p python3 a
      # - . a/bin/activate
